# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

# automatically return from the subprocess
promptToReturnFromSubprocess: false

gui:
  nerdFontsVersion: '3'

