hs.loadSpoon("LeftRightHotkey")
leftRightHotkey = spoon.LeftRightHotkey

local aerospace = "/usr/local/bin/aerospace"
leftRightHotkey:bind({ "l⌥" }, "l", function()
  os.execute(aerospace .. " focus right")
end)
leftRightHotkey:bind({ "l⌥", "lshift" }, "l", function()
  os.execute(aerospace .. " move right")
end)

leftRightHotkey:bind({ "l⌥" }, "c", function()
  os.execute(aerospace .. " workspace C")
end)
leftRightHotkey:bind({ "l⌥", "lshift" }, "c", function()
  os.execute(aerospace .. " move-node-to-workspace C")
end)
leftRightHotkey:bind({ "l⌥", "rshift" }, "c", function()
  os.execute(aerospace .. " move-node-to-workspace C")
end)
leftRightHotkey:bind({ "l⌥" }, "n", function()
  os.execute(aerospace .. " workspace N")
end)
leftRightHotkey:bind({ "l⌥", "lshift" }, "n", function()
  os.execute(aerospace .. " move-node-to-workspace N")
end)
leftRightHotkey:bind({ "l⌥", "rshift" }, "n", function()
  os.execute(aerospace .. " move-node-to-workspace N")
end)
leftRightHotkey:bind({ "l⌥" }, "z", function()
  os.execute(aerospace .. " workspace Z")
end)
leftRightHotkey:bind({ "l⌥", "lshift" }, "z", function()
  os.execute(aerospace .. " move-node-to-workspace Z")
end)
leftRightHotkey:bind({ "l⌥", "rshift" }, "z", function()
  os.execute(aerospace .. " move-node-to-workspace Z")
end)

leftRightHotkey:start()
