[settings]
minimum_release_age = "2d"
auto_update = true

[tools]
gh             = "latest"
java = "latest"
lua            = "5.1"
markdownlint-cli2 = "latest"
node           = "latest"
"npm:@przeprogramowani/10x-cli" = "latest"
"npm:ccstatusline" = "latest"
"npm:eslint"   = "latest"
"npm:prettier" = "latest"
pandoc         = "latest"
rust = "latest"
uv             = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
