[settings]
minimum_release_age = "2d"

[tools]
azure-cli      = { version = "latest", uvx_args = "--prerelease=allow --with pip" }
gh             = "latest"
go             = "latest"
imagemagick    = "latest"
lua            = "5.1"
node           = "latest"
"npm:eslint"   = "latest"
"npm:prettier" = "latest"
pandoc         = "latest"
rust = "latest"
uv             = "latest"
yt-dlp = { version = "latest", rename_exe = "yt-dlp" }
